### ISSUE TITLE
Plugin should automate tasks done by hand

### ISSUE THREAD

**Issue by frgomes** [scalajs-react-interface/sbt-sri-platform#4]
The plugin should provide tasks which automate tasks which are done by hand at the moment, like installing Android and iOS resources, like providing Expo support and related tasks.

This ticket is intended to track milestones only.
The actual discussion of milestones are separated in other tickes, reference here:

- [ ] M1: Support for SBT1.x :: https://github.com/scalajs-react-interface/sri/issues/15
- [ ] M2: Automate installation of platform resources :: #5
- [ ] M3: provide Expo support :: #6
- [ ] M4: provide common tasks to platform modules :: #7
- [ ] M5: enable acyclic plugin :: #8
